[package]
name = "kinetic-embed"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "sync", "time"] }

kinetic-core = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-kyn = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-network = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-storage = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-types = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-local = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-verify = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-action = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-primitives = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-kid = { git = "https://github.com/saifmukhtar/kinetic.git" }
kinetic-vdf = { git = "https://github.com/saifmukhtar/kinetic.git" }
hex = "0.4.3"
tracing = "0.1.44"
uniffi = { version = "0.32.2", features = ["cli"] }
uuid = { version = "1.26.1", features = ["v4"] }

[build-dependencies]
uniffi = { version = "0.32.2", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[lib]
crate-type = ["cdylib", "staticlib"]
